### ISSUE TITLE
Implement favicon and title for the Archive tool

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio-plus#146]
* Use the archive icon as favicon
* Use "`Archive / <Project name>`" (same as in the header) as the page title

![image](https://user-images.githubusercontent.com/11612490/127653985-40f3c824-f415-4706-b802-b1ff47ca8ccb.png)

**Comment by sigdestad** [comment]
How about always using CS icon as favicon? It will be confusing for users to change this depending on your current selected menu...

**Comment by sigdestad** [comment]
So, I'm suggesting we drop this issue

**Comment by alansemenov** [comment]
We cannot drop it, the icon is still missing. It's fine to use Content Studio's, but this has to be implemented. The title is wrong too.

**Comment by sigdestad** [comment]
Ok, but lets just use CS icon then :-)
