### ISSUE TITLE
Group restore events and refresh the grid once after restore

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio-plus#307]
1. Open Archive Browse Panel , select about 20 items and click on `Restore....` or `Delete...`
2. Click on Confirm button in `Confirm restore` dialog

**BUG** - Spinner appears several times and the grid is updated several times 
**Expected** 
1.  grid should be updated once when restore is completed. 

![image](https://user-images.githubusercontent.com/3728712/141455408-383a15c9-99cb-46b7-98de-bdcc913b51d8.png)

**Comment by alansemenov** [comment]
> @sgauruseu is it still actual after #299 ?

Yes - see video. There's also a problem with progress bar, it's just stuck on 100% while grid is being refreshed multiple times. Something is definitely wrong there.

https://user-images.githubusercontent.com/11612490/143212335-5ce6c36e-5300-4587-a24e-20b9736cf4f0.mov
