### ISSUE TITLE
Attachments Widget should not be shown in Details panel 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio-plus#322]
1. Go to Archive and select attachment content or an image
2. Open Details Panel
3.  Click on the link in  `Attachments Widget `

![image](https://user-images.githubusercontent.com/3728712/143898493-f4873bc8-d64b-455b-bca3-32f9e937353e.png)

**BUG**  - 500 error appears after clicking on the link, 
**Expected** -  Widget should not be shown in Details panel

**Comment by sigdestad** [comment]
I think widget should be shown, the real problem is that the attachment is not served.

**Comment by alansemenov** [comment]
To fix the attachment download we need to implement new API just for the Archive and I don't want to spend time on this now before the release. I'll create a backlog task to enable this.

**Comment by edloidas** [comment]
@alansemenov No, we actually don't. There is a missing check for `contentRootPath` in `Attachment`, so we just use the default, which is `'content'` (that is how we generate URLs for attachments). I'll create a task for this in app-contentstudio. This task should be closed, after the issue in app-contentstudio is solved.
