### ISSUE TITLE
Layers Content Tree Dialog is not updated after localizing/archiving a content 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio-plus#359]
**Case 1** 
1. Create a layer 
2. Select an inherited content in the layer and open `Layers Content Tree Dialog`
3. click on `Localize` button in the dialog
4.  save the localized content in new browser tab, close wizard

**BUG - `Localize` button should be updated to `Edit`** 

![image](https://user-images.githubusercontent.com/3728712/145200398-cd8a1fd1-a631-44f0-976a-76657b459cb9.png)

**Case 2** 

1. Create a layer 
2. Select an inherited content in the layer and open `Layers Content Tree Dialog`
3. click on `Localize` button in the dialog
4.  Click on `Archive...` button and delete the content.

 **BUG - deleted content is displayed in Layers Content Tree Dialog**

**Comment by ashklianko** [comment]
Pushed into https://github.com/enonic/app-contentstudio-plus/pull/388
